version: "3.9"

services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    init: true
    environment:
      TZ: Asia/Tokyo
      CHOKIDAR_USEPOLLING: 1
      HOST: 0.0.0.0
    working_dir: /bot/
    volumes:
      - ./bot/:/bot/
